// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One sanitized quota meter. It contains no provider or credential identity.
 */
export type AccountSlotQuotaMeter = { id: string, label: string | null, remainingPercent: number,
/**
 * Unix timestamp in seconds when this meter resets, or `null` when unknown.
 */
resetsAt: number | null, };
