// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginAppBrand } from "./LoginAppBrand";

/**
 * Starts or retries login for a server-managed account slot.
 *
 * Omitting `slotId` asks the server to allocate a private home and opaque slot id.
 */
export type AccountSlotLoginStartParams = { "type": "apiKey", slotId?: string | null, apiKey: string, } | { "type": "chatgpt", slotId?: string | null, codexStreamlinedLogin?: boolean, useHostedLoginSuccessPage?: boolean, appBrand?: LoginAppBrand | null, } | { "type": "chatgptDeviceCode", slotId?: string | null, } | { "type": "chatgptAuthTokens", slotId?: string | null, accessToken: string, chatgptAccountId: string, chatgptPlanType?: string | null, };
