// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountSlotQuotaMeter } from "./AccountSlotQuotaMeter";

/**
 * Sanitized quota projection used for display and account selection.
 */
export type AccountSlotQuotaSnapshot = { meters: Array<AccountSlotQuotaMeter>,
/**
 * Unix timestamp in seconds represented by this quota projection.
 */
observedAt: number,
/**
 * Unix timestamp in seconds after which the projection is stale.
 */
staleAt: number, };
