// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for reading a revision-consistent page of sanitized account slots.
 */
export type AccountSlotListParams = {
/**
 * Opaque cursor returned by a previous call. It is bound to the registry
 * revision and becomes stale after any same-process registry mutation.
 */
cursor?: string | null,
/**
 * Optional page size; the server applies a bounded default and maximum.
 */
limit?: number | null, };
