// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountSlotSnapshot } from "./AccountSlotSnapshot";

/**
 * Full changed-slot snapshot at a new registry revision.
 */
export type AccountSlotChangedNotification = { registryRevision: number, slot: AccountSlotSnapshot, };
