// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "../AuthMode";
import type { AccountSlotActionAvailability } from "./AccountSlotActionAvailability";
import type { AccountSlotHealth } from "./AccountSlotHealth";
import type { AccountSlotQuotaSnapshot } from "./AccountSlotQuotaSnapshot";
import type { AccountSlotStatus } from "./AccountSlotStatus";

/**
 * A global account projection without credential paths, email addresses, or tokens.
 */
export type AccountSlotSnapshot = {
/**
 * Stable logical account identity. Canonical global values are `C<N>`;
 * legacy local slot identifiers remain accepted for compatibility.
 */
accountSlotId: string,
/**
 * Stable global display and tie-break order.
 */
accountNumber: number, label: string, isDefault: boolean, status: AccountSlotStatus,
/**
 * Freshness and availability of the sanitized global projection.
 */
health: AccountSlotHealth,
/**
 * Sanitized quota meters supplied by the global account projection.
 */
quota: AccountSlotQuotaSnapshot | null, authMode: AuthMode | null, attemptGeneration: number, registryRevision: number, activeLoginOperationId: string | null, errorCode: string | null, actions: Array<AccountSlotActionAvailability>,
/**
 * Unix timestamp in seconds when the slot last changed.
 */
updatedAt: number, };
