// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountRotationSnapshot } from "./AccountRotationSnapshot";

export type AccountRotationReadResponse = {
/**
 * `null` means the global profile has not been activated yet.
 */
rotation: AccountRotationSnapshot | null, };
