// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountSlotLoginChallenge } from "./AccountSlotLoginChallenge";
import type { AccountSlotSnapshot } from "./AccountSlotSnapshot";
import type { SessionRuntimeOperation } from "./SessionRuntimeOperation";

export type AccountSlotLoginStartResponse = { slot: AccountSlotSnapshot, operation: SessionRuntimeOperation, challenge: AccountSlotLoginChallenge | null, };
