// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitSnapshot } from "./RateLimitSnapshot";

export type AccountSlotRateLimitsReadResponse = { accountSlotId: string, attemptGeneration: number,
/**
 * Unix timestamp in seconds when the rate-limit snapshot was captured.
 */
capturedAt: number,
/**
 * Unix timestamp in seconds after which this snapshot is stale.
 */
staleAt: number, rateLimits: RateLimitSnapshot, rateLimitsByLimitId: { [key in string]?: RateLimitSnapshot }, };
