// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Signals that the global inventory was replaced or an account was removed.
 * Clients should refetch `accountSlot/list` from the first page.
 */
export type AccountSlotInventoryChangedNotification = { registryRevision: number, };
