// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compare-and-swap parameters for logging out a secondary account slot.
 */
export type AccountSlotLogoutParams = { accountSlotId: string, expectedRegistryRevision: number, expectedAttemptGeneration: number, };
