// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitSnapshot } from "./RateLimitSnapshot";
import type { SessionRuntimeAccountRef } from "./SessionRuntimeAccountRef";

/**
 * Sparse rolling rate-limit update.
 *
 * Clients should merge available values into the most recent matching
 * `account/rateLimits/read` response or refetch that snapshot. New producers omit the
 * notification when persisted account provenance is unavailable; nullable fields preserve wire
 * compatibility with older producers.
 */
export type AccountRateLimitsUpdatedNotification = {
/**
 * Thread whose persisted turn binding produced this update.
 */
threadId: string | null,
/**
 * Persisted account binding for that turn. Older producers may leave this `null`.
 */
executionAccount: SessionRuntimeAccountRef | null, rateLimits: RateLimitSnapshot, };
