// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "../AuthMode";
import type { AccountSlotActionAvailability } from "./AccountSlotActionAvailability";
import type { AccountSlotStatus } from "./AccountSlotStatus";

/**
 * A host-managed account slot without credential paths, email addresses, or tokens.
 */
export type AccountSlotSnapshot = { accountSlotId: string,
/**
 * Stable display order within this app-server's account registry.
 */
accountNumber: number, label: string, isDefault: boolean, status: AccountSlotStatus, authMode: AuthMode | null, attemptGeneration: number, registryRevision: number, activeLoginOperationId: string | null, errorCode: string | null, actions: Array<AccountSlotActionAvailability>,
/**
 * Unix timestamp in seconds when the slot last changed.
 */
updatedAt: number, };
