// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountSlotAction } from "./AccountSlotAction";

export type AccountSlotActionAvailability = { action: AccountSlotAction, allowed: boolean, denyReason: string | null, };
