// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountSlotCapability } from "./AccountSlotCapability";
import type { AccountSlotSnapshot } from "./AccountSlotSnapshot";

/**
 * A revision-consistent page of sanitized account slots.
 */
export type AccountSlotListResponse = { data: Array<AccountSlotSnapshot>,
/**
 * Opaque cursor bound to `registryRevision` and a stable sort anchor. A stale-cursor
 * error requires restarting from the first page.
 */
nextCursor: string | null, registryRevision: number, multiAccount: AccountSlotCapability, };
