// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyAppPathString } from "../LegacyAppPathString";
import type { OverriddenMetadata } from "./OverriddenMetadata";
import type { WriteStatus } from "./WriteStatus";

export type ConfigWriteResponse = { status: WriteStatus, version: string,
/**
 * Canonical path to the config file that was written.
 */
filePath: LegacyAppPathString, overriddenMetadata: OverriddenMetadata | null, };
