// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyAppPathString } from "../LegacyAppPathString";
import type { PatchChangeKind } from "./PatchChangeKind";

export type FileUpdateChange = { path: LegacyAppPathString, kind: PatchChangeKind, diff: string, };
