// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { RateLimitResetCreditsSummary } from "./RateLimitResetCreditsSummary";
import type { RateLimitSnapshot } from "./RateLimitSnapshot";
import type { SessionRuntimeAccountRef } from "./SessionRuntimeAccountRef";

export type GetAccountRateLimitsResponse = {
/**
 * The exact thread subject used for this read, or `null` for legacy process-default reads.
 */
threadId: string | null,
/**
 * The account runtime captured for `thread_id`, or `null` for process-default reads.
 */
executionAccount: SessionRuntimeAccountRef | null,
/**
 * Backward-compatible single-bucket view; mirrors the historical payload.
 */
rateLimits: RateLimitSnapshot,
/**
 * Multi-bucket view keyed by metered `limit_id` (for example, `codex`).
 */
rateLimitsByLimitId: { [key in string]?: RateLimitSnapshot } | null, rateLimitResetCredits: RateLimitResetCreditsSummary | null,
/**
 * Account associated with this usage snapshot, when supplied by the backend.
 */
accountId: string | null,
/**
 * Optional backend-owned banner from the same usage read. Its nested keys retain the
 * backend's snake_case contract; an absent banner leaves the client's existing UI unchanged.
 */
rateLimitUpsell: JsonValue | null, };
