// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyAdmissionState } from "./LegacyAdmissionState";

/**
 * Sanitized state for a cutover-only legacy admission seal.
 */
export type LegacyAdmissionSnapshot = { cutoverEpoch: string, appServerInstanceGeneration: string, state: LegacyAdmissionState, inFlightMutationCount: number, };
