// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transition state for one Relay-managed legacy app-server admission seal.
 */
export type LegacyAdmissionState = "sealing" | "drained" | "aborted";
