// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginCommandTarget } from "./PluginCommandTarget";

export type PluginCommand = { id: string, pluginId: string, canonicalName: string, shortName: string | null, description: string, target: PluginCommandTarget, available: boolean, denyReason: string | null, };
