// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginCommandMcpToolResult } from "./PluginCommandMcpToolResult";
import type { ThreadGoal } from "./ThreadGoal";

export type PluginCommandInvokeResponse = { "type": "prompt", prompt: string, } | { "type": "mcpTool", result: PluginCommandMcpToolResult, } | { "type": "goalGet", goal: ThreadGoal | null, } | { "type": "goalSet", goal: ThreadGoal, } | { "type": "goalClear", cleared: boolean, } | { "type": "executable", exit_code: number | null, output: string, timed_out: boolean, } | { "type": "unavailable", deny_reason: string, };
