// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyAppPathString } from "../LegacyAppPathString";

export type PluginSource = { "type": "local", path: LegacyAppPathString, } | { "type": "git", url: string, path: LegacyAppPathString | null, refName: string | null, sha: string | null, } | { "type": "npm", package: string,
/**
 * Optional npm version or version range.
 */
version: string | null,
/**
 * Optional HTTPS registry URL. Authentication stays in the user's npm config.
 */
registry: string | null, } | { "type": "remote" };
