// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type PluginCommandMcpToolResult = { content: Array<JsonValue>, structuredContent: JsonValue | null, isError: boolean | null, _meta: JsonValue | null, };
