// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sanitized operation failure; it never contains tokens, paths, sockets, or raw PIDs.
 */
export type SessionRuntimeOperationError = { code: string, message: string, };
