// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRuntimePersistenceHealth } from "./SessionRuntimePersistenceHealth";
import type { SessionRuntimePersistencePosition } from "./SessionRuntimePersistencePosition";

/**
 * Durable JSONL/SQLite progress and health without exposing storage paths.
 */
export type SessionRuntimePersistence = { jsonl: SessionRuntimePersistencePosition | null, sqlite: SessionRuntimePersistencePosition | null,
/**
 * Number of durable records by which SQLite trails JSONL, when known.
 */
lag: number | null, flushHealth: SessionRuntimePersistenceHealth, materializeHealth: SessionRuntimePersistenceHealth,
/**
 * Unix timestamp in seconds of the last successful recorder flush.
 */
flushedAt: number | null,
/**
 * Unix timestamp in seconds of the last successful SQLite materialization.
 */
materializedAt: number | null, denyReason: string | null, };
