// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRuntimeLifecycleState } from "./SessionRuntimeLifecycleState";
import type { SessionRuntimeWaitingOn } from "./SessionRuntimeWaitingOn";

/**
 * Current lifecycle, subscription, and activity state for a thread.
 */
export type SessionRuntimeLifecycle = { state: SessionRuntimeLifecycleState, activeTurnId: string | null, waitingOn: Array<SessionRuntimeWaitingOn>, subscriberCount: number,
/**
 * Opaque client incarnation identifiers; raw process identifiers are never exposed.
 */
clientIncarnations: Array<string>,
/**
 * Unix timestamp in seconds of the most recent runtime activity.
 */
lastActivityAt: number | null,
/**
 * Unix timestamp in seconds when an idle unload is scheduled.
 */
unloadAt: number | null, };
