// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRuntimeOperation } from "./SessionRuntimeOperation";

/**
 * Progress or terminal state for a bounded process-local operation.
 */
export type SessionRuntimeOperationUpdatedNotification = { instanceEpoch: string, sequence: number, operation: SessionRuntimeOperation, };
