// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitInfo } from "./GitInfo";
import type { ThreadSettings } from "./ThreadSettings";

/**
 * Sanitized identity and settings that remain useful outside the Codex process.
 */
export type SessionRuntimeIdentity = { sessionId: string, forkedFromId: string | null, parentThreadId: string | null, name: string | null,
/**
 * Stable sanitized source name from the thread metadata.
 */
source: string, cwd: string, gitInfo: GitInfo | null,
/**
 * Effective next-turn settings when the thread is loaded and they are available.
 */
settings: ThreadSettings | null, };
