// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadTransitionReceipt } from "./ThreadTransitionReceipt";

export type SessionRuntimeContinuity = { lastIncoming: ThreadTransitionReceipt | null, lastOutgoing: ThreadTransitionReceipt | null, };
