// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRuntimeSnapshot } from "./SessionRuntimeSnapshot";

/**
 * Full changed-thread snapshot on the process runtime event stream.
 */
export type SessionRuntimeChangedNotification = { instanceEpoch: string, sequence: number, snapshot: SessionRuntimeSnapshot, };
