// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One named process capability and its current availability.
 */
export type SessionRuntimeCapability = {
/**
 * Stable capability name, such as `ananke_session_identity_v1`.
 */
name: string, available: boolean, denyReason: string | null, };
