// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRuntimeAction } from "./SessionRuntimeAction";

export type SessionRuntimeActionAvailability = { action: SessionRuntimeAction, allowed: boolean, denyReason: string | null, };
