// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRuntimeAccountBinding } from "./SessionRuntimeAccountBinding";
import type { SessionRuntimeActionAvailability } from "./SessionRuntimeActionAvailability";
import type { SessionRuntimeContinuity } from "./SessionRuntimeContinuity";
import type { SessionRuntimeIdentity } from "./SessionRuntimeIdentity";
import type { SessionRuntimeLifecycle } from "./SessionRuntimeLifecycle";
import type { SessionRuntimePersistence } from "./SessionRuntimePersistence";
import type { SessionRuntimeWriter } from "./SessionRuntimeWriter";

/**
 * Complete sanitized runtime state for one thread.
 */
export type SessionRuntimeSnapshot = {
/**
 * Logical runtime entity key.
 */
threadId: string,
/**
 * Monotonic revision used by thread control compare-and-swap requests.
 */
stateRevision: number, identity: SessionRuntimeIdentity, lifecycle: SessionRuntimeLifecycle, writer: SessionRuntimeWriter, persistence: SessionRuntimePersistence, account: SessionRuntimeAccountBinding, actions: Array<SessionRuntimeActionAvailability>, continuity: SessionRuntimeContinuity, };
