// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for reading a revision-consistent page of session runtime snapshots.
 */
export type SessionRuntimeListParams = {
/**
 * Opaque cursor returned by a previous call. The server rejects it when the
 * instance epoch or snapshot sequence no longer matches the source snapshot.
 */
cursor?: string | null,
/**
 * Optional page size; the server applies a bounded default and maximum.
 */
limit?: number | null,
/**
 * Optional exact thread identifier filter.
 */
threadId?: string | null, };
