// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRuntimeOperationAction } from "./SessionRuntimeOperationAction";
import type { SessionRuntimeOperationError } from "./SessionRuntimeOperationError";
import type { SessionRuntimeOperationStatus } from "./SessionRuntimeOperationStatus";

/**
 * Common operation state returned by controls and published as progress changes.
 */
export type SessionRuntimeOperation = { operationId: string,
/**
 * Opaque digest of the normalized action and arguments. Reusing an operation id
 * with a different fingerprint is an invalid request rather than an idempotent retry.
 */
requestFingerprint: string, action: SessionRuntimeOperationAction, status: SessionRuntimeOperationStatus, threadId: string | null, accountSlotId: string | null, stateRevision: number | null, writerGeneration: number | null, executionGeneration: number | null, error: SessionRuntimeOperationError | null,
/**
 * Unix timestamp in seconds when this operation state was produced.
 */
updatedAt: number, };
