// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRuntimeCapability } from "./SessionRuntimeCapability";
import type { SessionRuntimeSnapshot } from "./SessionRuntimeSnapshot";

/**
 * A revision-consistent page of complete session runtime snapshots.
 */
export type SessionRuntimeListResponse = { data: Array<SessionRuntimeSnapshot>,
/**
 * Opaque cursor bound to `instanceEpoch`, `snapshotSequence`, and a stable
 * sort anchor. A stale-cursor error requires restarting from the first page.
 */
nextCursor: string | null,
/**
 * Opaque identifier for this app-server process incarnation.
 */
instanceEpoch: string,
/**
 * Event sequence captured for every page in this snapshot.
 */
snapshotSequence: number,
/**
 * Process capabilities that external consumers may safely rely on.
 */
capabilities: Array<SessionRuntimeCapability>, };
