// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRuntimeWriterState } from "./SessionRuntimeWriterState";

/**
 * Writer ownership and its durable lease fence.
 */
export type SessionRuntimeWriter = { state: SessionRuntimeWriterState,
/**
 * Opaque store identity. This is not a filesystem path or process identifier.
 */
storeId: string | null, writerGeneration: number | null, denyReason: string | null, };
