// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRuntimeAccountRef } from "./SessionRuntimeAccountRef";
import type { SessionRuntimeAccountSwitchState } from "./SessionRuntimeAccountSwitchState";
import type { ThreadAccountRotationSnapshot } from "./ThreadAccountRotationSnapshot";

/**
 * Current and active-turn account provenance for a thread.
 */
export type SessionRuntimeAccountBinding = { current: SessionRuntimeAccountRef | null, activeTurn: SessionRuntimeAccountRef | null, rotation: ThreadAccountRotationSnapshot | null, switchState: SessionRuntimeAccountSwitchState, switchTargetSlotId: string | null, denyReason: string | null, };
