// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillsListParams = {
/**
 * When set, resolve account-bound plugins for this thread.
 */
threadId?: string | null,
/**
 * When empty, defaults to the current session working directory.
 */
cwds?: Array<string>,
/**
 * When true, bypass the skills cache and re-scan skills from disk.
 */
forceReload?: boolean, };
