// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalStatus } from "./ThreadGoalStatus";

export type ThreadGoalSetParams = { threadId: string, expectedGoalId?: string | null, expectedRevision?: number, objective?: string | null, status?: ThreadGoalStatus | null, tokenBudget?: number | null, };
