// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadTransitionReason } from "./ThreadTransitionReason";
import type { ThreadTransitionStatus } from "./ThreadTransitionStatus";
import type { ThreadWriterEvidence } from "./ThreadWriterEvidence";

export type ThreadTransitionPreparation = { transitionId: string, reason: ThreadTransitionReason, previousThreadId: string, currentThreadId: string, originInstanceEpoch: string, initiatorClientIncarnation: string, previousWriter: ThreadWriterEvidence, currentWriter: ThreadWriterEvidence, status: ThreadTransitionStatus, };
