// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadPresentationNoticeLevel } from "./ThreadPresentationNoticeLevel";

export type ThreadPresentation = { "type": "card", id: string, title: string, body: string, } | { "type": "notice", id: string, level: ThreadPresentationNoticeLevel, message: string, } | { "type": "progress", id: string, label: string, current: number, total: number | null, };
