// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadAccountRotationMode } from "./ThreadAccountRotationMode";

export type ThreadAccountRotationSnapshot = { mode: ThreadAccountRotationMode, fixedAccountSlotId: string | null, automaticAccountSlotIds: Array<string>, revision: number, lastCommittedAccountSlotId: string | null, };
