// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalStatus } from "./ThreadGoalStatus";

export type ThreadGoal = { threadId: string,
/**
 * Missing values decode as the legacy sentinel for stock-server compatibility.
 */
goalId: string,
/**
 * Missing values decode as the legacy sentinel for stock-server compatibility.
 */
revision: number, objective: string, status: ThreadGoalStatus, tokenBudget: number | null, tokensUsed: number, timeUsedSeconds: number, createdAt: number, updatedAt: number, };
