// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compare-and-swap parameters for switching a thread's next-turn account.
 */
export type ThreadAccountSwitchParams = { operationId: string, threadId: string, targetAccountSlotId: string, expectedInstanceEpoch: string, expectedStateRevision: number, expectedExecutionGeneration: number, };
