// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadTransitionEndpointEvidence } from "./ThreadTransitionEndpointEvidence";
import type { ThreadTransitionReason } from "./ThreadTransitionReason";
import type { ThreadTransitionStatus } from "./ThreadTransitionStatus";

export type ThreadTransitionReceipt = { transitionId: string, reason: ThreadTransitionReason, previous: ThreadTransitionEndpointEvidence, current: ThreadTransitionEndpointEvidence, originInstanceEpoch: string, initiatorClientIncarnation: string, transitionRevision: number, committedAt: number, status: ThreadTransitionStatus, };
