// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoal } from "./ThreadGoal";

export type ThreadGoalClearResponse = { cleared: boolean, previousGoal?: ThreadGoal,
/**
 * Missing values decode as the legacy sentinel for stock-server compatibility.
 */
revision: number, };
