// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadTransitionReason } from "./ThreadTransitionReason";
import type { ThreadWriterEvidence } from "./ThreadWriterEvidence";

export type ThreadTransitionIntent = { transitionId: string, reason: ThreadTransitionReason, previousThreadId: string, expectedInstanceEpoch: string, expectedStateRevision: number, expectedWriter: ThreadWriterEvidence, };
