// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadAccountRotationMode } from "./ThreadAccountRotationMode";

export type ThreadAccountRotationUpdateParams = { threadId: string, expectedRotationRevision: number, mode: ThreadAccountRotationMode, fixedAccountSlotId?: string | null, automaticAccountSlotIds: Array<string>, };
