// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionRuntimeAccountRef } from "./SessionRuntimeAccountRef";
import type { UserInput } from "./UserInput";

export type TurnSteerParams = {threadId: string, /**
 * Exact execution account expected by the client that produced this input.
 */
expectedExecutionAccount?: SessionRuntimeAccountRef | null, clientUserMessageId?: string | null, input: Array<UserInput>, /**
 * Required active turn id precondition. The request fails when it does not
 * match the currently active turn.
 */
expectedTurnId: string};
